import Image from "next/image";
import type { Metadata } from "next";
import Link from "next/link";
import { SitePage } from "@/Components/SitePage";
export const metadata: Metadata = { title: "Our Work and Impact", description: "Explore Elenii Shepherd's offline AI, assistive wearable, national community reach, DDQIC partnership and entrepreneurship incubator roadmap.", alternates: { canonical: "/work" } };
const milestones = [
  ["2,000+ reached", "More than 2,000 people reached and counting through research, demonstrations, accessibility engagement and entrepreneurship activity."],
  ["Three city networks", "Access to Nigerian Association of the Blind chapter networks in Jos, Abuja and Lagos."],
  ["Hybrid product system", "An offline-first accessibility application and ultrasonic wearable developed as connected parts of one product ecosystem."],
  ["Hardware progress", "Prototype testing completed, PCB design completed and submitted for manufacturing, with miniaturisation as the next product step."],
  ["Strategic DDQIC partnership", "A formal collaboration with the Dunin-Deshpande Innovation Centre at Queen's University focused on accessibility and entrepreneurship."],
  ["April 2026 founder session", "A dedicated hybrid entrepreneurship session in Jos supported visually impaired JLMCFF participants with problem validation and design thinking."],
  ["Accessible founder development", "Visually impaired founders in the Jim Leech Mastercard Foundation Fellowship Nigerian Chapter received dedicated in-person support, prototype development and collaborative learning through Elenii Shepherd."],
  ["Capacity strengthened", "Completed the Sahara Group Foundation SIF & MADAA Programme 2025 capacity-building workshop."],
  ["International recognition", "Invited to showcase at AT Village during Inclusive Africa Conference 2026 in Nairobi."],
  ["Incubator in development", "A dedicated visually impaired-centred entrepreneurship incubator is being prepared for launch later in 2026."],
];
export default function WorkPage() { return <SitePage eyebrow="OUR WORK" title="Three pieces of one problem." intro="Technology can improve access. Mentorship can turn an idea into a venture. Networks and capital can help that venture grow. We are connecting those pieces.">
  <section className="px-5 py-20"><div className="mx-auto max-w-7xl"><div className="grid gap-16 lg:grid-cols-2 lg:items-center"><div><p className="eyebrow">01 / ACCESS</p><h2 className="section-title">Offline-first accessibility</h2><p className="body-copy">An Android-centred application direction built around African connectivity realities, including voice guidance, OCR-based reading, navigation support and locally relevant content.</p></div><div className="relative aspect-[4/3]"><Image src="/media/device-fitting.jpeg" alt="Detail of an early wearable prototype" fill className="object-cover"/></div></div><div className="my-20 border-t border-slate-300"/><div className="grid gap-16 lg:grid-cols-2 lg:items-center"><div className="relative aspect-[4/3] lg:order-1"><Image src="/media/device-production.jpeg" alt="Wearable housings during prototype production" fill className="object-cover"/></div><div className="lg:order-2"><p className="eyebrow">02 / HARDWARE</p><h2 className="section-title">Affordable obstacle sensing</h2><p className="body-copy">A wearable assistive device using ultrasonic sensing, embedded systems and simple physical controls. The current prototype proves the concept; the next work is making it smaller, more practical and affordable.</p></div></div><div className="my-20 border-t border-slate-300"/><div className="grid gap-16 lg:grid-cols-2 lg:items-center"><div><p className="eyebrow">03 / OPPORTUNITY</p><h2 className="section-title">An entrepreneurship pathway</h2><p className="body-copy">A visually impaired-centred incubator model moving through selection, training, mentorship, venture development, pitching, funding opportunities and growth.</p><Link href="/opportunities" className="mt-7 inline-block border-b-2 border-secondary pb-1 font-bold">See ways to take part →</Link></div><div className="relative aspect-[4/3]"><Image src="/media/community-circle.jpeg" alt="Community members gathered during a field session" fill className="object-cover"/></div></div></div></section>
  <section className="border-y border-slate-300 bg-white px-5 py-20"><div className="mx-auto max-w-7xl"><p className="eyebrow">ACCOMPLISHMENTS SO FAR</p><h2 className="section-title">Proof of work, not vanity numbers.</h2><div className="mt-10">{milestones.map(([title,text],i)=><article key={title} className="grid gap-4 border-t border-slate-300 py-7 sm:grid-cols-[80px_260px_1fr]"><span className="font-mono text-sm text-primary">{String(i+1).padStart(2,"0")}</span><h3 className="font-bold">{title}</h3><p className="max-w-2xl text-slate-600">{text}</p></article>)}</div></div></section>
  <section className="bg-[#dcebf5] px-5 py-20"><div className="mx-auto max-w-7xl"><p className="eyebrow">STRATEGIC PARTNERSHIP</p><div className="mt-8 grid gap-12 lg:grid-cols-[1.1fr_.9fr]"><div><h2 className="text-4xl font-bold tracking-tight sm:text-5xl">Elenii Shepherd × DDQIC at Queen&apos;s University</h2><p className="mt-6 max-w-3xl text-lg leading-8 text-slate-700">The partnership is focused on two connected priorities: strengthening accessibility and inclusion for visually impaired fellows within the Jim Leech Mastercard Foundation Fellowship in Nigeria, and launching a dedicated programme that builds entrepreneurship skills, confidence, income pathways and leadership opportunities.</p></div><div className="border-l-4 border-primary pl-7"><p className="text-sm font-bold uppercase tracking-[.16em] text-primary">Why it matters</p><p className="mt-4 text-xl font-semibold leading-8">It connects community access in Nigeria with the entrepreneurship expertise, mentorship and global network of one of Queen&apos;s University&apos;s leading innovation centres.</p><a href="https://www.queensu.ca/innovationcentre/" className="mt-7 inline-block border-b-2 border-primary pb-1 font-bold" target="_blank" rel="noreferrer">Visit DDQIC →</a></div></div></div></section>
  <section className="bg-[#f7f4ed] px-5 py-20"><div className="mx-auto max-w-7xl"><p className="eyebrow">ROADMAP / 2026–2027</p><div className="mt-10 grid gap-px bg-slate-300 md:grid-cols-2 lg:grid-cols-4">{[["Now","Complete user research across the three NAB chapter networks and deepen community-led product validation."],["Next","Miniaturise the wearable, advance PCB manufacturing and improve the offline accessibility application."],["Launch","Open the Elenii Shepherd Incubator with accessible training, mentorship and venture-development support."],["Scale","Build funding pathways, expand delivery beyond the initial states and establish a repeatable Nigerian model with wider African relevance."]].map(([stage,text])=><article key={stage} className="bg-[#f7f4ed] p-7"><p className="font-mono text-sm font-bold text-primary">{stage}</p><p className="mt-8 leading-7 text-slate-700">{text}</p></article>)}</div></div></section>
  <section className="overflow-hidden bg-[#071e33] py-9 text-white"><div className="partner-track flex min-w-max items-center gap-16 px-8 text-xl font-bold"><span>DDQIC · Queen&apos;s University</span><span className="text-secondary">•</span><span>JLMCFF Nigeria ecosystem</span><span className="text-secondary">•</span><span>University of Jos community</span><span className="text-secondary">•</span><span>AT Village · Inclusive Africa 2026</span><span className="text-secondary">•</span><span aria-hidden>DDQIC · Queen&apos;s University</span><span className="text-secondary">•</span><span aria-hidden>JLMCFF Nigeria ecosystem</span></div></section>
  </SitePage>; }
