import Image from "next/image";
import type { Metadata } from "next";
import { SitePage } from "@/Components/SitePage";
export const metadata: Metadata = { title: "Field Gallery", description: "Real photographs and films from Elenii Shepherd's assistive-technology development, community testing and outreach in Nigeria.", alternates: { canonical: "/gallery" } };
const photographs = [
  ["/media/community-circle.jpeg", "Community testing", "Jos · 2025", "A field session brings users, builders and observers into the same conversation."], ["/media/community-testing.jpeg", "Trying the wearable", "Jos · 2025", "A participant examines the wearable during a group demonstration."], ["/media/device-production.jpeg", "Made by hand", "Prototype workshop · 2025", "Wearable housings during local production and assembly."], ["/media/event-portrait-2.jpeg", "Out in the ecosystem", "Technology gathering · 2025", "The wearable shown in a wider technology community."], ["/media/wearable-demo.jpeg", "Learning the controls", "Field notes · 2026", "Hands-on product exploration during a user session."], ["/media/field-walk.jpeg", "Moving together", "Jos · 2026", "Testing beyond the desk, in the conditions where the product must work."], ["/media/device-detail.jpeg", "Inside the prototype", "Development archive", "Ultrasonic sensing integrated into an early wearable form."], ["/media/field-team.jpeg", "Listening first", "Community visit · 2026", "A conversation before a product decision."],
];
export default function GalleryPage() { return <SitePage eyebrow="THE FIELD ARCHIVE" title="The work, without the stock photography." intro="Photographs and short films from prototype development, user testing, outreach and the people shaping Elenii Shepherd.">
  <section className="px-5 py-16"><div className="mx-auto grid max-w-7xl gap-x-6 gap-y-12 sm:grid-cols-2 lg:grid-cols-3">{photographs.map(([src,title,date,caption], i) => <figure key={src} className={i % 5 === 0 ? "sm:col-span-2" : ""}><div className={`relative overflow-hidden bg-slate-200 ${i % 5 === 0 ? "aspect-[16/9]" : "aspect-[4/5]"}`}><Image src={src} alt={caption} fill className="object-cover" sizes="(max-width: 768px) 100vw, 40vw"/></div><figcaption className="border-t border-slate-400 pt-3"><div className="flex justify-between gap-4"><strong>{title}</strong><span className="text-sm text-slate-500">{date}</span></div><p className="mt-2 max-w-lg text-sm leading-6 text-slate-600">{caption}</p></figcaption></figure>)}</div></section>
  <section className="bg-[#071e33] px-5 py-20 text-white"><div className="mx-auto max-w-7xl"><p className="text-xs font-bold uppercase tracking-[.18em] text-blue-200">FIELD FILMS</p><div className="mt-8 grid gap-8 lg:grid-cols-2"><Video src="/media/videos/20250625_183228.mp4" poster="/media/community-circle.jpeg" title="Community prototype session"/><Video src="/media/videos/james-story.mp4" poster="/media/field-walk.jpeg" title="A short moment with James"/><Video src="/media/videos/20250625_184405.mp4" poster="/media/community-testing.jpeg" title="Testing notes"/><Video src="/media/videos/20250625_182714.mp4" poster="/media/device-production.jpeg" title="Prototype in use"/></div></div></section>
  </SitePage>; }
function Video({src,poster,title}:{src:string;poster:string;title:string}) { return <figure><video className="aspect-video w-full bg-black object-cover" controls preload="metadata" poster={poster}><source src={src} type="video/mp4"/></video><figcaption className="mt-3 border-t border-white/20 pt-3 font-semibold">{title}</figcaption></figure>; }
