import Image from "next/image";
import Link from "next/link";
import { FaArrowRight, FaMicrochip, FaRegNewspaper } from "react-icons/fa";
import { HiOutlineLightBulb, HiOutlineWifi } from "react-icons/hi";
import Navbar from "@/Components/Navbar";
import { Footer } from "@/Components/Footer";

const work = [
  { icon: HiOutlineWifi, label: "Offline-first AI", text: "Accessibility, navigation, voice guidance and reading tools designed for places where data is expensive or unreliable." },
  { icon: FaMicrochip, label: "Assistive hardware", text: "An affordable wearable prototype using ultrasonic sensing to help people detect nearby obstacles." },
  { icon: HiOutlineLightBulb, label: "Entrepreneurship", text: "A dedicated incubation pathway connecting visually impaired founders to training, mentors, networks and funding opportunities." },
];

export default function Home() {
  return <main className="min-h-screen bg-white"><Navbar/>
    <section className="relative overflow-hidden border-b border-slate-300 bg-[#f7f4ed] pt-28 lg:pt-32"><div className="mx-auto grid min-h-[760px] max-w-7xl items-center gap-12 px-5 pb-20 lg:grid-cols-[1.02fr_.98fr] lg:px-8">
      <div className="relative z-10"><p className="eyebrow">ACCESS • INDEPENDENCE • OPPORTUNITY</p><h1 className="mt-6 max-w-3xl text-5xl font-bold leading-[1.02] tracking-[-.045em] text-slate-950 sm:text-6xl lg:text-7xl">The future belongs to <span className="text-primary">every kind of vision.</span></h1><p className="mt-7 max-w-xl text-lg leading-8 text-slate-600">Elenii Shepherd is building a connected ecosystem where visually impaired children, young people and adults can access technology, learn, move independently, create and participate fully in the economy.</p>
      <div className="mt-9 flex flex-wrap gap-4"><Link href="#story" className="btn-primary flex items-center gap-3 rounded-full px-7 py-4 font-bold">Discover our story <FaArrowRight/></Link><Link href="#contact" className="rounded-full border border-slate-300 bg-white px-7 py-4 font-bold text-slate-800 hover:border-primary">Work with us</Link></div>
      <div className="mt-12 grid max-w-xl grid-cols-3 gap-5 border-t border-slate-300 pt-7"><div><strong className="stat">2,000+</strong><span className="stat-label">people reached and counting</span></div><div><strong className="stat">3</strong><span className="stat-label">NAB chapter networks</span></div><div><strong className="stat">2026</strong><span className="stat-label">incubator launch year</span></div></div></div>
      <div className="relative mx-auto w-full max-w-[570px] self-end"><div className="relative h-[610px] overflow-hidden border border-slate-300"><Image src="/media/wearable-user.jpeg" alt="A visually impaired participant testing Elenii Shepherd's wearable assistive device" fill className="object-cover" priority sizes="(max-width: 1024px) 100vw, 50vw"/></div><div className="border-x border-b border-slate-300 bg-white p-5"><p className="text-xs font-bold uppercase tracking-[.18em] text-primary">Field testing / Jos</p><p className="mt-2 text-lg font-semibold">Built through direct engagement—not assumptions.</p></div></div>
    </div></section>

    <section id="story" className="section-pad scroll-mt-20 bg-white"><div className="mx-auto grid max-w-7xl gap-14 px-5 lg:grid-cols-2 lg:items-center lg:px-8"><div className="relative grid grid-cols-2 gap-4"><div className="relative mt-16 h-[370px] overflow-hidden"><Image src="/media/field-walk.jpeg" alt="The team walking with a visually impaired participant during field research" fill className="object-cover" sizes="25vw"/></div><div className="relative h-[370px] overflow-hidden"><Image src="/media/field-team.jpeg" alt="An Elenii Shepherd team member speaking with a participant" fill className="object-cover" sizes="25vw"/></div></div><div><p className="eyebrow">OUR REACH</p><h2 className="section-title">Built with communities across Jos, Abuja and Lagos.</h2><p className="body-copy">More than 2,000 people have now been reached—and the number is still growing—through research, demonstrations, accessibility engagement and entrepreneurship activity. Access to Nigerian Association of the Blind chapter networks in three cities gives the work a stronger base for sustained community-led design.</p><p className="body-copy mt-5">What people shared expanded the mission beyond a single product. Access also means affordable devices, reliable offline functionality, mentorship, business opportunity and a place in the wider innovation economy.</p><blockquote className="mt-8 border-l-4 border-secondary pl-6 text-xl font-semibold leading-relaxed text-slate-800">“The best accessibility solutions have to be designed around the realities of the people who will use them.”</blockquote></div></div></section>

    <section id="work" className="section-pad scroll-mt-20 bg-[#dcebf5]"><div className="mx-auto max-w-7xl px-5 lg:px-8"><div className="max-w-3xl"><p className="eyebrow">ONE CONNECTED ECOSYSTEM</p><h2 className="section-title">Independence is more than a product feature.</h2><p className="body-copy">We connect tools for everyday access with pathways to economic independence. Each part strengthens the next.</p></div><div className="mt-12 grid gap-px bg-slate-400 md:grid-cols-3">{work.map(({icon: Icon,label,text}) => <article key={label} className="bg-white p-8"><div className="flex h-12 w-12 items-center justify-center bg-primary text-xl text-white"><Icon/></div><h3 className="mt-7 text-2xl font-bold text-slate-950">{label}</h3><p className="mt-4 leading-7 text-slate-600">{text}</p></article>)}</div></div></section>

    <section className="border-y border-slate-300 bg-white px-5 py-16"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-[.85fr_1.15fr] lg:items-center lg:px-3"><div><p className="eyebrow">STRATEGIC PARTNERSHIP</p><p className="mt-4 text-2xl font-bold">DDQIC · Queen&apos;s University, Canada</p></div><div><h2 className="text-3xl font-bold tracking-tight sm:text-4xl">Building accessible entrepreneurship pathways together.</h2><p className="mt-5 leading-7 text-slate-600">The partnership strengthens inclusion for visually impaired participants in the Jim Leech Mastercard Foundation Fellowship and supports the launch of a dedicated entrepreneurship programme for visually impaired people in Nigeria and beyond.</p><Link href="/work" className="mt-6 inline-block border-b-2 border-secondary pb-1 font-bold">Read about the partnership →</Link></div></div></section>

    <section className="section-pad overflow-hidden bg-[#071e33] text-white"><div className="mx-auto grid max-w-7xl gap-12 px-5 lg:grid-cols-[.9fr_1.1fr] lg:items-center lg:px-8"><div><p className="eyebrow text-blue-200">WHY OFFLINE MATTERS</p><h2 className="mt-5 text-4xl font-bold tracking-tight sm:text-5xl">When connectivity fails, accessibility should not.</h2><p className="mt-6 text-lg leading-8 text-slate-300">Many digital tools assume continuous internet access. In Nigeria, unreliable or expensive data can become another barrier. That is why offline functionality is central to our product direction—not an afterthought.</p><div className="mt-9 grid grid-cols-2 divide-x divide-white/20 border-y border-white/20"><div className="py-5 pr-5"><strong className="text-secondary">Mobile accessibility</strong><p className="mt-2 text-sm text-slate-300">Voice guidance, OCR, text and sign reading.</p></div><div className="py-5 pl-5"><strong className="text-secondary">Locally relevant</strong><p className="mt-2 text-sm text-slate-300">Designed for the devices and conditions people already have.</p></div></div></div><div className="relative h-[560px] overflow-hidden"><Image src="/media/device-fitting.jpeg" alt="Close view of the wearable assistive device being fitted" fill className="object-cover" sizes="50vw"/></div></div></section>

    <section id="impact" className="section-pad scroll-mt-20 bg-white"><div className="mx-auto max-w-7xl px-5 lg:px-8"><div className="grid gap-12 lg:grid-cols-2"><div><p className="eyebrow">MOMENTUM</p><h2 className="section-title">Community reach, product progress and founder outcomes.</h2></div><p className="body-copy lg:pt-10">The organisation is moving on several fronts at once: deeper national community access, practical hardware development, accessible entrepreneurship delivery and international collaboration.</p></div><div className="mt-12 grid gap-px overflow-hidden bg-slate-200 md:grid-cols-2">{[
      ["2,000+ people reached", "Research, demonstrations, accessibility engagement and entrepreneurship activity across a growing community."], ["Hardware development", "PCB design completed and submitted for manufacturing; miniaturisation and practical everyday use are next."], ["Inclusive founder development", "Visually impaired founders are participating in the Jim Leech Mastercard Foundation Fellowship Nigerian Chapter with dedicated in-person support from Elenii Shepherd."], ["Three NAB networks", "Access to Nigerian Association of the Blind chapter networks in Jos, Abuja and Lagos."],
    ].map(([title,text]) => <article key={title} className="bg-blue-50 p-8 sm:p-10"><p className="text-sm font-bold uppercase tracking-wider text-primary">{title}</p><p className="mt-4 text-lg leading-8 text-slate-700">{text}</p></article>)}</div></div></section>

    <section className="section-pad bg-amber-50"><div className="mx-auto grid max-w-7xl gap-12 px-5 lg:grid-cols-[1.05fr_.95fr] lg:items-center lg:px-8"><div className="relative h-[590px] overflow-hidden"><Image src="/media/wearable-demo.jpeg" alt="A participant exploring the controls of the wearable device with the team" fill className="object-cover" sizes="50vw"/></div><div><p className="eyebrow">LAUNCHING LATER IN 2026</p><h2 className="section-title">The Elenii Shepherd Incubator.</h2><p className="body-copy">A dedicated entrepreneurship pathway being built for visually impaired founders—from early ideas to viable ventures, stronger networks and funding opportunities.</p><div className="mt-8 flex flex-wrap gap-2">{["Selection","Training","Mentorship","Venture development","Pitching","Funding opportunities","Growth"].map((item,i)=><span key={item} className="border border-amber-300 bg-white px-4 py-2 text-sm font-bold text-slate-700"><span className="mr-2 text-primary">{String(i+1).padStart(2,"0")}</span>{item}</span>)}</div><p className="mt-8 border-l-4 border-secondary bg-white p-5 text-sm leading-6 text-slate-600"><strong className="text-slate-950">Partnerships are open now.</strong> Elenii Shepherd is strengthening accessibility, curriculum, mentorship, participant support and funding pathways ahead of launch.</p><Link href="/opportunities" className="mt-7 inline-block border-b-2 border-slate-950 pb-1 font-bold">See how to participate →</Link></div></div></section>

    <section id="media" className="section-pad scroll-mt-20 bg-white"><div className="mx-auto max-w-7xl px-5 lg:px-8"><div className="mb-10 flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><p className="eyebrow">IN THE FIELD</p><h2 className="section-title mb-0">See the work, as it happens.</h2></div><p className="max-w-lg text-slate-600">Real moments from prototype testing, community engagement and building alongside the people the technology is intended to serve.</p></div><div className="grid gap-4 md:grid-cols-3"><div className="relative h-[480px] overflow-hidden md:col-span-2"><Image src="/media/IMG_1635.webp" alt="Elenii Shepherd community engagement" fill className="object-cover" sizes="66vw"/></div><div className="relative h-[480px] overflow-hidden"><Image src="/media/wearable-portrait.jpeg" alt="Participant wearing the Elenii Shepherd prototype" fill className="object-cover" sizes="33vw"/></div></div><div className="mt-4 overflow-hidden bg-slate-950"><video className="aspect-video w-full object-cover" controls preload="metadata" poster="/media/device-detail.jpeg"><source src="/media/elenii-story.mp4" type="video/mp4"/>Your browser does not support video.</video></div></div></section>

    <section className="border-y border-slate-300 bg-[#f7f4ed] px-5 py-16"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-[1fr_auto] lg:items-center"><div><p className="eyebrow">TEST THE TECHNOLOGY</p><h2 className="mt-4 max-w-3xl text-4xl font-bold tracking-tight">The Android prototype is now available for public testing.</h2><p className="mt-5 max-w-2xl leading-7 text-slate-600">Download version 0.1.0, try the current build and help the team understand what works in real use.</p></div><Link href="/prototype" className="border-b-4 border-secondary pb-2 text-xl font-bold">Open the test page →</Link></div></section>

    <section className="bg-white px-5 py-20"><div className="mx-auto max-w-7xl"><div className="grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><div><p className="eyebrow">FROM LINKEDIN</p><h2 className="section-title">Follow the work as it moves.</h2><p className="body-copy">Field notes, programme news and partnership updates are published through Elenii Shepherd&apos;s official LinkedIn page.</p><a href="https://ng.linkedin.com/company/elenii-shepherd" target="_blank" rel="noreferrer" className="mt-7 inline-block border-b-2 border-[#0a66c2] pb-1 font-bold text-[#0a66c2]">Follow Elenii Shepherd on LinkedIn ↗</a></div><div>{[["4 July 2026","Visually impaired founders in the Nigerian fellowship chapter met in person to develop and pitch prototypes."],["11 April 2026","A dedicated hybrid founder session in Jos moved participants from business foundations into problem validation."],["Strategic partnership","Elenii Shepherd and DDQIC at Queen's University announced work on accessibility and entrepreneurship pathways."]].map(([date,text])=><article key={date} className="grid gap-3 border-t border-slate-300 py-6 sm:grid-cols-[150px_1fr]"><p className="text-sm font-bold text-primary">{date}</p><p className="leading-7 text-slate-700">{text}</p></article>)}</div></div></div></section>

    <section id="contact" className="scroll-mt-20 bg-[#2a77aa] px-5 py-20 text-white"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-[1fr_auto] lg:items-center lg:px-3"><div><div className="mb-5 flex items-center gap-2 text-sm font-bold uppercase tracking-[.16em] text-blue-100"><FaRegNewspaper/> For media & partners</div><h2 className="max-w-4xl text-4xl font-bold tracking-tight sm:text-5xl">Help us build an innovation economy where visual impairment does not limit ambition.</h2><p className="mt-6 max-w-2xl text-lg leading-8 text-blue-100">For interviews, demonstrations, research conversations, partnerships or programme support, speak directly with the Elenii Shepherd team.</p></div><Link href="/contact" className="flex items-center justify-center gap-3 rounded-full bg-secondary px-8 py-4 font-bold text-slate-950 shadow-lg hover:bg-amber-300">Start a conversation <FaArrowRight/></Link></div></section>
    <Footer/>
  </main>;
}
